### ISSUE TITLE
Import error: No module named 'models.ops.depthconv._ext.depthconv._depthconv'

### ISSUE THREAD

**Issue by Elena-ssq** [iriszero/DepthAwareCNNplus#1]
Hi, when I try to run train.py, this import error occurs. Any clue why this happens? Thank you.

**Comment by iriszero** [comment]
You have to compile it first. Scripts for that is written in the directory *script*.

**Comment by Elena-ssq** [comment]
Thanks for the help.
I have already run the scripts and compile submodules. No errors occurred during the procedure. However the problem still exits.
